name: "Build and Deploy Jekyll Blog"

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll b -d _site
        env:
          JEKYLL_ENV: "production"

      - name: Test site
        run: |
          bundle exec htmlproofer _site \
            --disable-external \
            --ignore-urls "/^http:\/\/127.0.0.1/,/^http:\/\/0.0.0.0/,/^http:\/\/localhost/"
            --check-img-http false \          # Add this line to disable image checking
            --check-opengraph false           # Add this line to disable OpenGraph checking
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

  # REPLACED DEPLOY JOB: Uses peaceiris/action-gh-pages to deploy to an EXTERNAL repository
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pages-artifact
          path: _site

      - name: Deploy to Blog Folder
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Use a PAT that has write access to the TARGET repo (hansworld.github.io)
          personal_token: ${{ secrets.PAT_TOKEN }}
          # Publish the built site files
          publish_dir: ./_site
          # The IMPORTANT part: Target your main portfolio repository
          external_repository: maxrayman/maxrayman.github.io
          # The CRITICAL part: Deploy to the 'blog' subfolder
          destination_dir: blog
          # Force overwrite the blog folder completely
          force_orphan: true
          commit_message: "Deploy Jekyll Blog: ${{ github.sha }}"